create or replace package AOC21_P12 as

    procedure part_one(pIn in varchar2,pOut in out varchar2);
    procedure part_two(pIn in varchar2, pOut in out varchar2);

end;
/
create or replace package body AOC21_P12 as

    /*
        -- DDL

            CREATE TABLE  "AOC21_D12_INPUT" 
            (	"ID" NUMBER GENERATED BY DEFAULT AS IDENTITY , 
                "COL001" VARCHAR2(1000), 
                CONSTRAINT "AOC21_D12_INPUT_PK" PRIMARY KEY ("ID")
            USING INDEX  ENABLE
            ) 

            CREATE TABLE  "AOC21_D12_CAVE" 
            (	"DACAVE" VARCHAR2(4000), 
                "ACAVE" VARCHAR2(4000)
            )            

            CREATE TABLE  "AOC21_D12_PATH" 
            (	"PATH" VARCHAR2(4000), 
                "LAST" VARCHAR2(4000), 
                "STEP" NUMBER, 
                "TWICE" VARCHAR2(4000)
            )            

     */

    procedure part_one(pIn in varchar2, pOut in out varchar2)
    is
        vCount number;
        vStep number;
    begin

        DELETE FROM AOC21_D12_INPUT;

        INSERT INTO AOC21_D12_INPUT(ID,COL001)
        select rownum id, column_value col001 from table(apex_string.split(replace(pIn,chr(13),''),chr(10)));

        DELETE FROM AOC21_D12_CAVE;

        INSERT INTO AOC21_D12_CAVE(dacave,acave)
            SELECT regexp_substr(t.col001,'[^-]+',1,1) dacave,  regexp_substr(t.col001,'[^-]+',1,2) acave 
            FROM AOC21_D12_INPUT t;

        INSERT INTO AOC21_D12_CAVE(dacave,acave)
            SELECT acave, dacave
            FROM AOC21_D12_CAVE;        

        delete from AOC21_D12_PATH;

        insert into AOC21_D12_PATH(PATH,LAST,STEP)
            VALUES('start','start',1);    
        
        vCount := 1;
        vStep := 1;
        WHILE vCount > 0
            LOOP

                insert into AOC21_D12_PATH(PATH,LAST,STEP)
                    SELECT p.PATH||','||c.acave PATH,  c.acave LAST, (vStep+1) STEP 
                    FROM AOC21_D12_CAVE c, AOC21_D12_PATH p
                    WHERE p.last <> 'end' and c.dacave = p.last and p.step = vStep and
                        ( ( lower(c.acave) <> c.acave) 
                            or c.acave not in (select column_value from table(apex_string.split(p.PATH,',')) )
                        );

                SELECT count(*)
                    INTO vCount
                    FROM AOC21_D12_PATH 
                    WHERE STEP = vStep;

                vStep := vStep +1;

                htp.prn('STEP='||vStep||'; COUNT='||vCount||'<BR />');

            END LOOP;

        SELECT count(*)
            INTO pOut
            FROM AOC21_D12_PATH 
            WHERE LAST = 'end';            
    end;

    procedure part_two(pIn in varchar2, pOut in out varchar2)
    is
        vCount number;
        vStep number;
    begin

        DELETE FROM AOC21_D12_INPUT;

        INSERT INTO AOC21_D12_INPUT(ID,COL001)
        select rownum id, column_value col001 from table(apex_string.split(replace(pIn,chr(13),''),chr(10)));

        DELETE FROM AOC21_D12_CAVE;

        INSERT INTO AOC21_D12_CAVE(dacave,acave)
            SELECT regexp_substr(t.col001,'[^-]+',1,1) dacave,  regexp_substr(t.col001,'[^-]+',1,2) acave 
            FROM AOC21_D12_INPUT t;

        INSERT INTO AOC21_D12_CAVE(dacave,acave)
            SELECT acave, dacave
            FROM AOC21_D12_CAVE;    

        delete from AOC21_D12_PATH; 

        FOR CCC IN (SELECT distinct dacave FROM AOC21_D12_CAVE where dacave not in ('start','end') )
        LOOP

            delete FROM  AOC21_D12_CAVE WHERE dacave = 'xxxxxxxxxx' or acave = 'xxxxxxxxxx';        

            INSERT INTO AOC21_D12_CAVE(dacave,acave)
                SELECT 'xxxxxxxxxx', acave
                FROM AOC21_D12_CAVE WHERE dacave = CCC.dacave;

            INSERT INTO AOC21_D12_CAVE(dacave,acave)
                SELECT dacave, 'xxxxxxxxxx'
                FROM AOC21_D12_CAVE WHERE acave = CCC.dacave;               

            insert into AOC21_D12_PATH(PATH,LAST,STEP,TWICE)
                VALUES('start','start',1,CCC.dacave);    
            
            vCount := 1;
            vStep := 1;
            WHILE vCount > 0
                LOOP

                    insert into AOC21_D12_PATH(PATH,LAST,STEP,TWICE)
                        SELECT p.PATH||','||c.acave PATH,  c.acave LAST, (vStep+1) STEP , CCC.dacave TWICE
                        FROM AOC21_D12_CAVE c, AOC21_D12_PATH p
                        WHERE p.last <> 'end' and c.dacave = p.last and p.step = vStep and p.TWICE = CCC.dacave and
                            ( ( lower(c.acave) <> c.acave) 
                                or c.acave not in (select column_value from table(apex_string.split(p.PATH,',')) )
                            );

                    SELECT count(*)
                        INTO vCount
                        FROM AOC21_D12_PATH 
                        WHERE STEP = vStep and TWICE = CCC.dacave;

                    vStep := vStep +1;

                    htp.prn('STEP='||vStep||'; COUNT='||vCount||'<BR />');

                END LOOP;

            UPDATE AOC21_D12_PATH
                SET PATH = replace(PATH,'xxxxxxxxxx',CCC.dacave)
                WHERE TWICE = CCC.dacave;

        END LOOP;

        SELECT count(*)
            INTO pOut
            FROM ( SELECT DISTINCT PATH
            FROM AOC21_D12_PATH 
            WHERE LAST = 'end');          
    end;

end;
/
declare
    vOut varchar2(100);
begin

    AOC21_P12.part_one(pIn => 'yw-MN
wn-XB
DG-dc
MN-wn
yw-DG
start-dc
start-ah
MN-start
fi-yw
XB-fi
wn-ah
MN-ah
MN-dc
end-yw
fi-end
th-fi
end-XB
dc-XB
yw-XN
wn-yw
dc-ah
MN-fi
wn-DG',pOut => vOut);
    htp.prn('part one: illopa says '||vOut||'<BR />');
 
    AOC21_P12.part_two(pIn => 'yw-MN
wn-XB
DG-dc
MN-wn
yw-DG
start-dc
start-ah
MN-start
fi-yw
XB-fi
wn-ah
MN-ah
MN-dc
end-yw
fi-end
th-fi
end-XB
dc-XB
yw-XN
wn-yw
dc-ah
MN-fi
wn-DG', pOut => vOut);
    htp.prn('part two: illopa says '||vOut||'<BR />');
end;